# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions:
  contents: read


jobs:
  api:
    name: api-check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install ruff
        run: python -m pip install --upgrade pip && python -m pip install ruff

      - name: Install the project (uv sync)
        run: uv sync --locked --all-extras --dev

      - name: Run ruff --fix
        run: uv run ruff check --fix .

      - name: Run tests
        run: uv run pytest tests/test_api.py

  playwright:
    name: playwright-tests
    needs: api
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project (uv sync)
        run: uv sync --locked --all-extras --dev

      - name: Install Playwright browsers
        run: uv run playwright install

      - name: Run Playwright tests
        run: uv run pytest tests/test_gui.py